// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMngr.Data;

#nullable disable

namespace TaskMngr.Migrations
{
    [DbContext(typeof(TaskDb))]
    [Migration("20231121133334_AddTableAndSeedData")]
    partial class AddTableAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskMngr.Models.Tsk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tsks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Task 1",
                            Name = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Task 2",
                            Name = "Task 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Task 3",
                            Name = "Task 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Task 4",
                            Name = "Task 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Task 5",
                            Name = "Task 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
